<div style="text-align: center;">
  <h1 style="background-color: #1B4B5E; color: white; padding: 10px 20px; margin-bottom: 20px; border-radius: 8px;">Predict Unseen Data</h1>
</div>

In [33]:
import pickle
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Read Unseen Data

In [34]:
df_test = pd.read_csv('test_data_finpro.csv')
df_test.head(5)

,Customer,State,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Customer Lifetime Value
0,ZQ59828,California,No,Basic,High School or Below,1/17/11,Employed,M,74585,Rural,...,0,1,Personal Auto,Personal L3,Offer2,Agent,218.598065,SUV,Medsize,4222.631209
1,XM45289,Oregon,No,Basic,High School or Below,2/1/2011,Employed,F,23218,Suburban,...,0,4,Personal Auto,Personal L2,Offer4,Agent,447.793440,Two-Door Car,Medsize,5514.344018
2,GP20408,Oregon,Yes,Extended,College,1/28/11,Employed,F,94903,Suburban,...,0,1,Personal Auto,Personal L3,Offer2,Agent,451.200000,Two-Door Car,Small,3808.122147
3,WQ46946,California,No,Extended,College,9/2/2011,Employed,F,77153,Urban,...,1,5,Personal Auto,Personal L3,Offer1,Branch,355.641958,Four-Door Car,Medsize,7914.823110
4,HK93338,Washington,No,Basic,High School or Below,2/20/11,Disabled,F,23769,Suburban,...,0,2,Personal Auto,Personal L2,Offer1,Branch,470.097411,Four-Door Car,Medsize,7931.722181

In [35]:
df_test.drop(columns=["Effective To Date", "Customer", "Customer Lifetime Value"], inplace=True)
df_test.head(5)

,State,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,California,No,Basic,High School or Below,Employed,M,74585,Rural,Married,106,...,49,0,1,Personal Auto,Personal L3,Offer2,Agent,218.598065,SUV,Medsize
1,Oregon,No,Basic,High School or Below,Employed,F,23218,Suburban,Single,71,...,10,0,4,Personal Auto,Personal L2,Offer4,Agent,447.793440,Two-Door Car,Medsize
2,Oregon,Yes,Extended,College,Employed,F,94903,Suburban,Married,94,...,38,0,1,Personal Auto,Personal L3,Offer2,Agent,451.200000,Two-Door Car,Small
3,California,No,Extended,College,Employed,F,77153,Urban,Married,99,...,27,1,5,Personal Auto,Personal L3,Offer1,Branch,355.641958,Four-Door Car,Medsize
4,Washington,No,Basic,High School or Below,Disabled,F,23769,Suburban,Divorced,69,...,14,0,2,Personal Auto,Personal L2,Offer1,Branch,470.097411,Four-Door Car,Medsize

# Load Model Random Forest

In [36]:
with open('model/final_model_rf.pkl', 'rb') as file:
    loaded_model_rf = pickle.load(file)

# Load Model Kmeans

In [37]:
with open('model/final_model_kmeans.pkl', 'rb') as file:
    loaded_model_kmeans = pickle.load(file)

# Predict Regression

In [38]:
predictions = loaded_model_rf.predict(df_test)
print(predictions)

[ 4223.6259723   5507.33017805  3807.10903607 ...  4609.66364166
  2201.77534471 11947.80971601]

In [39]:
df_test['Customer Lifetime Value'] = predictions
df_test.head(5)

,State,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Customer Lifetime Value
0,California,No,Basic,High School or Below,Employed,M,74585,Rural,Married,106,...,0,1,Personal Auto,Personal L3,Offer2,Agent,218.598065,SUV,Medsize,4223.625972
1,Oregon,No,Basic,High School or Below,Employed,F,23218,Suburban,Single,71,...,0,4,Personal Auto,Personal L2,Offer4,Agent,447.793440,Two-Door Car,Medsize,5507.330178
2,Oregon,Yes,Extended,College,Employed,F,94903,Suburban,Married,94,...,0,1,Personal Auto,Personal L3,Offer2,Agent,451.200000,Two-Door Car,Small,3807.109036
3,California,No,Extended,College,Employed,F,77153,Urban,Married,99,...,1,5,Personal Auto,Personal L3,Offer1,Branch,355.641958,Four-Door Car,Medsize,7890.315462
4,Washington,No,Basic,High School or Below,Disabled,F,23769,Suburban,Divorced,69,...,0,2,Personal Auto,Personal L2,Offer1,Branch,470.097411,Four-Door Car,Medsize,8721.120295

# Predict Clustering

In [40]:
clusters = loaded_model_kmeans.fit_predict(df_test)

In [41]:
df_test['Cluster'] = clusters
df_test.head(5)

,State,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,...,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Customer Lifetime Value,Cluster
0,California,No,Basic,High School or Below,Employed,M,74585,Rural,Married,106,...,1,Personal Auto,Personal L3,Offer2,Agent,218.598065,SUV,Medsize,4223.625972,1
1,Oregon,No,Basic,High School or Below,Employed,F,23218,Suburban,Single,71,...,4,Personal Auto,Personal L2,Offer4,Agent,447.793440,Two-Door Car,Medsize,5507.330178,1
2,Oregon,Yes,Extended,College,Employed,F,94903,Suburban,Married,94,...,1,Personal Auto,Personal L3,Offer2,Agent,451.200000,Two-Door Car,Small,3807.109036,1
3,California,No,Extended,College,Employed,F,77153,Urban,Married,99,...,5,Personal Auto,Personal L3,Offer1,Branch,355.641958,Four-Door Car,Medsize,7890.315462,0
4,Washington,No,Basic,High School or Below,Disabled,F,23769,Suburban,Divorced,69,...,2,Personal Auto,Personal L2,Offer1,Branch,470.097411,Four-Door Car,Medsize,8721.120295,0

In [45]:
df_test.groupby("Cluster")["Customer Lifetime Value"].mean().sort_values(ascending=False)

Cluster
2    13744.508915
0     8621.416947
1     4021.394377
Name: Customer Lifetime Value, dtype: float64

<div style="text-align: center;">
  <h1 style="background-color: #1B4B5E; color: white; padding: 10px 20px; margin-bottom: 20px; border-radius: 8px;">Summary</h1>
</div>

The prediction of Customer Lifetime Value (CLV) using the Random Forest model and subsequent clustering analysis has provided valuable insights into customer segmentation. Based on the predictions, customers have been categorized into three distinct clusters:

- Gold Cluster (Cluster 2): This segment consists of high-value customers with significant profitability potential. It is crucial to implement strategies focused on retention and upselling premium services to this group.

- Silver Cluster (Cluster 0): This cluster includes moderate-value customers who present opportunities for growth. Tailored marketing efforts aimed at enhancing engagement can help elevate these customers to the Gold Cluster.

- Bronze Cluster (Cluster 1): Customers in this segment represent lower value, highlighting the need for targeted interventions to improve retention and increase their lifetime value.

This analysis emphasizes the importance of leveraging predictive modeling and clustering techniques to develop targeted marketing strategies, optimize resource allocation, and ultimately drive better customer engagement and profitability for CAV AutoInsurance.